import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import Navbar from './components/Navbar'
import Sidebar from './components/sidebar/Sidebar'
import Content from './components/content/Content'

const nunito = Nunito({ subsets: ['latin']})

export const metadata: Metadata = {
  title: 'students2modules',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Navbar />
          {/* <Sidebar />
          <Content /> */}
        <main className="px-4 md:px-6 prose prose-xl prose-slate dark:prose-invert mx-auto">
          {children}
        </main>
      </body>
    </html>
  )
}
